# Numpy

In this section we'll briefly introduce `numpy`,
arguably the most popular and widely-used library 
for numerical computing in Python.
We will start off by examining `numpy` ndarrays,
the core data structure that it offers, 
and give a hint of the vast capabilities it provides
including the efficient implementations of many
mathematical operators that can be performed on it.

The very first thing we need to do is import the package.
Most professionals will do this as follows: `import numpy as np`. 
The `import package_name as short_name` syntax 
just allows us to rename a library so for convenience.
Since we'll use numpy so often, we prefer to only type `np` each time.

In [1]:
import numpy as np

Now we can access all kinds of functions, objects, and special numbers from the numpy library. 
To begin with, we note that numpy provides a lot of the basic maths
that you are used to accessing via the `math` package. 
For example, `numpy` implements many useful constances, including $e$ and $\pi$.

In [2]:
print(np.e)
print(np.pi)

2.718281828459045
3.141592653589793


We can also access many familiar scalar functions through `numpy`, including (but not limited) to those we already encountered in `math`, e.g., `ceil()` and `sin()`.

In [5]:
np.ceil(np.e)
np.sin(np.pi/2)

1.0

We could not possibly cover every single function and still promise to offer a concise tutorial. However, to get a sense for the offering, you can introspect the package via `dir(np)` or take a look at the [official documentation](https://docs.scipy.org/doc/numpy-1.17.0/reference/).

## Numpy's ndarray

While `numpy` does provide an ample amount of functionality for manipulating scalars,
the key offering of the numpy library is the ndarray,
a powerful object for representing and manipulating n-dimensional arrays.
In short, Python's lists aim extreme flexibility---but 
come at the expense of extreme slowness.
Imagine, for example we wanted to work with a 2D array of floats:

In [7]:
matrix1 = [[0,1,2,3,4,5,6,7,8,9],[10,11,12,13,14,15,16,17,18,19],[20,21,22,23,24,25,26,27,28,29]]
print(matrix1)

[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9], [10, 11, 12, 13, 14, 15, 16, 17, 18, 19], [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]]


Now at this size, for most purposes, this list is fine. But say for example that we wanted to calculate the average value in the list. How might we do it? We'd likely have to iterate over all rows and all columns of the list.

In [8]:
total = 0
denominator = len(matrix1) * len(matrix1[0])
for row in range(len(matrix1)):
    for col in range(len(matrix1[0])):
        total += matrix1[row][col]
print(total/denominator)

14.5


This is problematic for a couple reasons. 
First, it's a lot of code to do a very standard numerical calculation. 
Second, in order facilitate the flexibility of Python's lists 
to store aribitrary objects, the numbers are very slow to access. 
It might seem fast to us (many thousands of accesses per second!) 
but compared to the same operation using arrays implemented efficiently in C, 
the performance of this code is just glacial. 

Numpy gives us an extremely optimized tools for storing 
and manipulating arrays comprised of elments
all of which are contstrained to assume the same type 
(selected among a restricted list of allowed types).
Later in this tutorial we will compare the compute time 
required by naive Python implementations vs highly-optimized numpy.

## Creating an NDArray 
The most intuitive way to instantiate a numpy ndarray
is by calling `numpy.array(...)` and passing 
a Python list literal (or list of lists) as an input.
Importantly, each element must be a float and the lengths
of the lists must line up to make this is a rectangular object.

In [12]:
vec1 = np.array([5,1,7,4,12,2])
vec1

array([ 5,  1,  7,  4, 12,  2])

Note that for a numpy list every element must be a numerical values
and they must all share the same type. 
Python will let us get away with composing mixed lists of 
functions, objects, classes, packages, floats, ints, and Booleans.
But numpy types are strictly enforced. 
This strictness in both the size and type of the array
allows for efficient implementations where each item
is stored in consecutive, fixed-size blocks of memory. 
We can  access the `type` of an ndarray via its `.dtype` attribute.

In [14]:
vec1.dtype

dtype('int64')

Note that numpy inferred that because we instantiated it with list of ints,
we must want the lements to be stored as ints. 
What happens now if we try to assign a float to the first index?

In [18]:
vec1[0] = 4.5
vec1

array([ 4,  1,  7,  4, 12,  2])

We can't do it! Numpy won't throw an error, but it will do a type conversion. 
Similar things happen if we try to assign a Boolean value.

In [21]:
vec1[0] = True
vec1[1] = False
vec1

array([ 1,  0,  7,  4, 12,  2])

The value `True` gets cast to the int `1` and the value `False` gets cast to `0`. 
If we try to assign a string, however, we'll get an error.

In [23]:
vec1[0] = "Banana"

ValueError: invalid literal for int() with base 10: 'Banana'

That's because the type conversion `int("Banana")` fails. Notice below that you get th same exact error message.

In [27]:
int("Banana")

ValueError: invalid literal for int() with base 10: 'Banana'

## Declaring the type
To explicitly set the type of an `ndarray` (e.g., as an `np.float64`), 
we can declare the type by using the named argument `dtype`
in the constructor e.g.: 

In [30]:
vec1 = np.array([5,1,7,4,12,2], dtype=np.float64)
vec1

array([ 5.,  1.,  7.,  4., 12.,  2.])

## Matrices
To create a two dimensional array from a literal,
we just pass in a list of lists, as follows:

In [33]:
matrix2 = np.array([[0.0,1,2,3,4,5,6,7,8,9],[10,11,12,13,14,15,16,17,18,19],[20,21,22,23,24,25,26,27,28,29]])
print(matrix2)

[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]
 [20. 21. 22. 23. 24. 25. 26. 27. 28. 29.]]


Notice that even though all the valeus besides the very first element of the first list are integers, the type of the list is float. Intuitively that's because floats are more general than ints (and ints are more general than Boolean values). There's a natural way to represent an int as a float without loss of information (up to numerical precision issues) but not vice-versa.

In [35]:
matrix2.dtype

dtype('float64')

In [37]:
np.array([True, 4, 5.5]).dtype

dtype('float64')

## Standard summary functions

It's now easy to access standard numperical functions 
either via the numpy library functinos or via 
the corresponding methods of the `ndarray` object.
This is very un-Pythonic---somehow there 
are multiple ways to do the same thing.
However, at this point so many trillions of lines 
depend on numpy that it might be too late 
to fix this so we are stuck with the inelegance. 
Below we calcualte the mean of the `ndarray`
both as a function in the `np` namespace and as  
a method of the `ndarray` object.

In [38]:
print(np.mean(matrix2))
print(matrix2.mean())

14.5
14.5


## Shape and Axes

An `ndarray` has (possibly) multiple axes. 
For a 2nd-order array (i.e. matrix),
we have two axes to work with. 
We can learn about the dimensions of an ndarray 
along each of its axes via the shape attribute:

In [39]:
matrix2.shape

(3, 10)

## Creating ndarrays programmatically 

There are many ways to create ndarrays. 
We already saw one: by using the `np.array(...)` function
on a Python list consisting of only numerical values.
We can also just call up lists of ones or zeros,
by passing the appropriate shape to the 
`np.ones()` and `np.zeros()` functions respectively.

In [42]:
ones_mat = np.ones((4,10))
zeros_mat = np.zeros((3,6))
print("Using ones: \n", ones_mat)
print("\nUsing zeros: \n", zeros_mat)

Using ones: 
 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

Using zeros: 
 [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


## `ones_like` and `zeros_like`
Given an `ndarray` of some shape, we often
want to create an ndarray of the exact same shape
but initialized to be all ones or all zeros. 
We could do this with `np.ones(matrix2.shape)`.
Numpy also gives us a more elegant shorthand:

In [49]:
print("With np.ones", np.ones(matrix2.shape))
print("\nWith np.ones_like", np.ones_like(matrix2))
print("\nWith np.zeros_like", np.zeros_like(matrix2))

With np.ones [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

With np.ones_like [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

With np.zeros_like [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


## Accessing values

We can access elements by punching in the indices along each axis separated by commas. 
Note that `my_array[i,j]` is equivalent to `my_array[i][j]`. Note that this indexing by tuple is supported in `numpy` but not with Python lists of lists (*hint: try it with matrix1*). 

In [51]:
print(matrix2[1,6])
print(matrix2[1][6])

16.0
16.0


## Updating values
Just as with any Python list, we can 

In [52]:
matrix2[1,6] = 314
print(matrix2)

[[  0.   1.   2.   3.   4.   5.   6.   7.   8.   9.]
 [ 10.  11.  12.  13.  14.  15. 314.  17.  18.  19.]
 [ 20.  21.  22.  23.  24.  25.  26.  27.  28.  29.]]


## Aggregating over a specific axis

For many operations to selectively apply the operation along a specific axis, we can specify the desired axis with a named argument. For example say that we want to compute the sum of our matrix, but only over each column:

In [53]:
np.sum(matrix2, axis=0)

array([ 30.,  33.,  36.,  39.,  42.,  45., 346.,  51.,  54.,  57.])

Note that the original array had shape (3, 10). The resulting array has shape (10). That's because we eliminated the first axis (`axis=0`) by summing over it. 
If instead, we sum over `axis 1`, we'll expect a result of dimension 3.

In [54]:
np.sum(matrix2, axis=1)

array([ 45., 443., 245.])

Similarly we can take the `max`, `min`, `argmax`, `argmin` and many other functions in a similar element-wise fashion.

## Ranges
We often want to initialize values to be consecutive numbers,
e.g., we might want all numbers between $0$ and $10$ in increments of $.2$.
We can do this in numpy ny using the `arange` function to construct an ndarray.
It functions similarly to Python ranges but
(i) creates an ndarray, not a `range` object;
and (ii) can handle fractional increments.

In [57]:
np.arange(0,10, .2)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4,
       2.6, 2.8, 3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. ,
       5.2, 5.4, 5.6, 5.8, 6. , 6.2, 6.4, 6.6, 6.8, 7. , 7.2, 7.4, 7.6,
       7.8, 8. , 8.2, 8.4, 8.6, 8.8, 9. , 9.2, 9.4, 9.6, 9.8])

## Random numbers
We can also create `ndarrays` populated with random numbers.
Numpy provides a whole sub-library to handle randomness. 
Aptly it lives in `np.random` and includes functions 
for creating arrays populated according to many popular distributions
including binomial, Dirichlet, gamma, exponential, multinomial, 
normal, pareto, uniform, weibull, etc.
One convenient function `np.random.randn()`
allows us to sample number from a standard (isotropic) Gaussian 
an `ndarray` with a given shape. 
Strangely here, we don't have to pack up the shape in a tuple.
Be careful that this is different from how we create a list of zeros or ones.

In [63]:
np.random.randn(3, 10)

array([[ 0.20809148, -0.31867457,  0.35556272,  1.38979668,  0.02263045,
        -0.29595989,  1.1094042 ,  0.27528824,  0.31161249,  0.52016895],
       [ 0.12143637,  0.86086166, -0.47710981,  0.9740589 ,  0.05434734,
         0.71645625, -0.18504702,  0.02060288,  0.31328557,  2.24053907],
       [ 1.31326439,  0.90711692, -1.65582049, -0.70284036,  0.28688899,
         1.93892638, -0.41170632,  0.31102391, -1.55628503, -1.01273554]])

## Element-wise operations

All of the basic scalar operations are *lifted* to high-dimensional arrays of equal dimensions. Here, they just operate by performing the operation on each pair of corresponding values. 

In [65]:
x = np.ones((4,3)) * 3
y = np.ones((4,3)) * 2

In [67]:
print("x", x)
print("y", y)
print("x + y", x + y)
print("x * y", x * y)
print("x / y", x / y)
print("x ** y", x ** y)

x [[3. 3. 3.]
 [3. 3. 3.]
 [3. 3. 3.]
 [3. 3. 3.]]
y [[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]
x + y [[5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]]
x * y [[6. 6. 6.]
 [6. 6. 6.]
 [6. 6. 6.]
 [6. 6. 6.]]
x / y [[1.5 1.5 1.5]
 [1.5 1.5 1.5]
 [1.5 1.5 1.5]
 [1.5 1.5 1.5]]
x ** y [[9. 9. 9.]
 [9. 9. 9.]
 [9. 9. 9.]
 [9. 9. 9.]]


We can also lift unary operators to matrix operations. 
For example, `np.exp` will exponentiate each element in a matrix $b_{ij} = e^{a_{ij}}$:

In [68]:
np.exp(x)

array([[20.08553692, 20.08553692, 20.08553692],
       [20.08553692, 20.08553692, 20.08553692],
       [20.08553692, 20.08553692, 20.08553692],
       [20.08553692, 20.08553692, 20.08553692]])

## Broadcasting

We can add or multiply scalars by matrices. Here numpy will just create an array of the same shape as the `ndarray` operand where every value is set equal to the scalar value and then perform the element-wise operation:

In [71]:
np.arange(10) * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [72]:
np.arange(10) + 1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

If we try to perform an operation on a 1D ndarray and a 2D ndarray, numpy will try to broadcast along the missing axis to make the operands be of the same shape. However, if the matrix is square and the ndarray to be broadcasted is 1D without an explicit axis of length 1, be careful that you know along which dimension it will be broadcasted. Consider the following:

In [76]:
x2 = np.arange(9).reshape((3,3))
print(x2)

vec2 = np.array([3,2,1])
print(x2 + vec2)
print(x2 + vec2.reshape((1,3)))
print(x2 + vec2.reshape((3,1)))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[3 3 3]
 [6 6 6]
 [9 9 9]]
[[3 3 3]
 [6 6 6]
 [9 9 9]]
[[3 4 5]
 [5 6 7]
 [7 8 9]]


## Basic Linear Algebra

In [77]:
print(x2)
print(x2.T)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 3 6]
 [1 4 7]
 [2 5 8]]


In [86]:
vec3 = np.arange(1,4)
print(vec3)
np.dot(vec3, vec3)

[1 2 3]


14

### Matrix-vector product

In [88]:
np.dot(x2, vec3)

array([ 8, 26, 44])

### Matrix-matrix product

In [89]:
np.dot(x2, x2.T)

array([[  5,  14,  23],
       [ 14,  50,  86],
       [ 23,  86, 149]])

### Eigenvalue decomposition

In [91]:
np.linalg.eig(x2)

(array([ 1.33484692e+01, -1.34846923e+00, -2.48477279e-16]),
 array([[ 0.16476382,  0.79969966,  0.40824829],
        [ 0.50577448,  0.10420579, -0.81649658],
        [ 0.84678513, -0.59128809,  0.40824829]]))

### Matrix inverse

In [96]:
x3 = [[1,7,2], [13, 4.5, 9], [12, 2, 9]]
x3_inv = np.linalg.inv(x3)
print(x3_inv)

[[-0.23316062  0.61139896 -0.55958549]
 [ 0.09326425  0.15544041 -0.1761658 ]
 [ 0.29015544 -0.84974093  0.89637306]]


### Speed

In [97]:
import time
list1 = [1] * 10000000
list2 = [2] * 10000000

start = time.time()
list3 = []
for i in range(len(list1)):
    list3.append(list1[i] + list2[i])
end = time.time()
print("Time elapsed:", end-start)

Time elapsed: 1.8881242275238037


in numpy...

In [98]:
npl1= np.ones(10000000)
npl2= np.ones(10000000)

start = time.time()
npl3 = npl1 + npl2
end = time.time()
print("Time elapsed:", end-start)

Time elapsed: 0.016360044479370117


#### Matmul

In [99]:
def matmul(A, B):
    N = len(A)
    K = len(A[0])
    M = len(B[1])
    
    
    C = []
    for i in range(N):
        C.append([])
        
    i = 0
    for m in range(M):
        for n in range(N):
            result = 0
            for k in range(K):
                i+=1
#                 print("iteration i", i)
                result += A[n][k] * B[k][m]
                
#             print("the result!", result)
            C[n].append(result)
    return C

In [100]:
x1 = [[1,2,3],[4,5,6], [7,8,9]]

matmul(x1,x1)

[[30, 36, 42], [66, 81, 96], [102, 126, 150]]

In [102]:
x1np = np.array(x1)
np.dot(x1np, x1np)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [103]:
N = 300
A = [[1] * N] * N

start = time.time()
matmul(A, A)
end = time.time()
print("Time elapsed:", end-start)

Time elapsed: 4.175977945327759


in numpy...

In [104]:
B = np.ones((N,N))

start = time.time()
np.dot(B,B)
end = time.time()
print("Time elapsed:", end-start)

Time elapsed: 0.0010769367218017578
